package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import movies.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:20:43 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi44 */
  @Test
  public void testRekisteroi44() {    // Genre: 44
    Genre testi1 = new Genre(); 
    Genre testi2 = new Genre(); 
    testi1.setId(5); 
    testi2.rekisteroi(); 
    assertEquals("From: Genre line: 49", 5, testi1.getId()); 
    assertEquals("From: Genre line: 50", 6, testi2.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse109 */
  @Test
  public void testParse109() {    // Genre: 109
    Genre testi= new Genre(); 
    testi.parse("1|komedia"); 
    assertEquals("From: Genre line: 112", true, testi.toString().equals("1|komedia")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString126 */
  @Test
  public void testToString126() {    // Genre: 126
    Genre testi= new Genre(); 
    testi.parse("1|komedia"); 
    assertEquals("From: Genre line: 129", true, testi.toString().equals("1|komedia")); 
  } // Generated by ComTest END
}