package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import movies.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:21:19 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenretTest {



  // Generated by ComTest BEGIN
  /** testGenret15 */
  @Test
  public void testGenret15() {    // Genret: 15
    Genret testit = new Genret(); 
    Genre testi1 = new Genre(); 
    Genre testi2 = new Genre(); 
    testi1.parse("99|1|8"); 
    testi2.rekisteroi(); 
    assertEquals("From: Genret line: 21", 0, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 23", 1, testit.getLkm()); 
    testit.lisaa(testi2); 
    assertEquals("From: Genret line: 25", 2, testit.getLkm()); 
    assertEquals("From: Genret line: 26", testi1, testit.getById(99)); 
    assertEquals("From: Genret line: 27", testi2, testit.getById(100)); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 29", 3, testit.getLkm()); 
    assertEquals("From: Genret line: 30", testi1, testit.get(0)); 
    assertEquals("From: Genret line: 31", testi2, testit.get(1)); 
    assertEquals("From: Genret line: 32", testi1, testit.get(2)); 
    testit.lisaa(testi2); 
    assertEquals("From: Genret line: 34", 4, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 36", 5, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 38", 6, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 40", 7, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: Genret line: 42", 8, testit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPaivita73 
   * @throws SailoException when error
   */
  @Test
  public void testPaivita73() throws SailoException {    // Genret: 73
    Genre testi1 = new Genre(); 
    Genre testi2 = new Genre(); 
    Genret testit = new Genret(); 
    testi1.parse("1|Marley & Me 2|7|ei|2011|-|-"); 
    testi2.parse("1|Fun Size|7|ei|2012|-|-"); 
    testit.lisaa(testi1); 
    testit.get(0).toString().equals("1|Marley & Me 2|7|ei|2011|-|-"); 
    testit.paivita(testi2); 
    testit.get(0).toString().equals("1|Fun Size|7|ei|2012|-|-"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista99 */
  @Test
  public void testPoista99() {    // Genret: 99
    Genret testit = new Genret(); 
    Genre testi1 = new Genre(); 
    Genre testi2 = new Genre(); 
    Genre testi3 = new Genre(); 
    testi1.parse("1|komedia"); 
    testi2.parse("8|satiiri"); 
    testi3.parse("10|kauhu"); 
    testit.lisaa(testi1); 
    testit.lisaa(testi2); 
    testit.lisaa(testi3); 
    assertEquals("From: Genret line: 110", 3, testit.getLkm()); 
    testit.poista(1); 
    assertEquals("From: Genret line: 112", 2, testit.getLkm()); 
    testit.poista(8); 
    testit.poista(7); 
    assertEquals("From: Genret line: 115", 1, testit.getLkm()); 
  } // Generated by ComTest END
}