package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static movies.Helpers.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:21:53 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HelpersTest {



  // Generated by ComTest BEGIN
  /** testTryParseInt42 */
  @Test
  public void testTryParseInt42() {    // Helpers: 42
    assertEquals("From: Helpers line: 43", 6, tryParseInt("6", 0)); 
    assertEquals("From: Helpers line: 44", 0, tryParseInt("", 0)); 
    assertEquals("From: Helpers line: 45", 0, tryParseInt("abc", 0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTryParseInt67 */
  @Test
  public void testTryParseInt67() {    // Helpers: 67
    assertEquals("From: Helpers line: 68", 6, tryParseInt("6", 0, 12, 0)); 
    assertEquals("From: Helpers line: 69", 0, tryParseInt("", 0, 12, 0)); 
    assertEquals("From: Helpers line: 70", 0, tryParseInt("abc", 0, 12, 0)); 
    assertEquals("From: Helpers line: 71", 0, tryParseInt("13", 0, 12, 0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIntToStringUnless94 */
  @Test
  public void testIntToStringUnless94() {    // Helpers: 94
    intToStringUnless(1, 0).equals("1"); 
    intToStringUnless(0, 0).equals(""); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testFindOptionIndex110 */
  @Test
  public void testFindOptionIndex110() {    // Helpers: 110
    String[] options = new String[] { "kissa", "koira", "hevonen"} ; 
    assertEquals("From: Helpers line: 112", 1, findOptionIndex(options, "koira", 0)); 
    assertEquals("From: Helpers line: 113", 0, findOptionIndex(options, "vauva", 0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testValidateIMDBUrl129 */
  @Test
  public void testValidateIMDBUrl129() {    // Helpers: 129
    assertEquals("From: Helpers line: 130", false, validateIMDBUrl(null)); 
    assertEquals("From: Helpers line: 131", false, validateIMDBUrl("")); 
    assertEquals("From: Helpers line: 132", false, validateIMDBUrl("asdfasijw")); 
    assertEquals("From: Helpers line: 133", true, validateIMDBUrl("https://www.imdb.com/title/tt1663143/")); 
  } // Generated by ComTest END
}