package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.ArrayList;
import movies.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:26:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LeffarekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista119 
   * @throws SailoException when error
   */
  @Test
  public void testPoista119() throws SailoException {    // Leffarekisteri: 119
    Leffarekisteri testi = new Leffarekisteri(); 
    Leffa testi1 = new Leffa(); 
    Genre komedia = new Genre(-1, "komedia"); 
    Genre satiiri = new Genre(-1, "satiiri"); 
    Genre kauhu = new Genre(-1, "kauhu"); 
    testi.tallenna(komedia); 
    testi.tallenna(satiiri); 
    testi.tallenna(kauhu); 
    testi.tallenna(testi1, new Genre[]{komedia, satiiri}); 
    assertEquals("From: Leffarekisteri line: 130", 2, testi.getLeffanGenretLkm()); 
    assertEquals("From: Leffarekisteri line: 131", 1, testi.getLeffoja()); 
    testi.poista(testi1.getId()); 
    assertEquals("From: Leffarekisteri line: 133", 0, testi.getLeffoja()); 
    assertEquals("From: Leffarekisteri line: 134", 0, testi.getLeffanGenretLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testOnkoMuokattu150 
   * @throws SailoException when error
   */
  @Test
  public void testOnkoMuokattu150() throws SailoException {    // Leffarekisteri: 150
    Leffarekisteri testi = new Leffarekisteri(); 
    assertEquals("From: Leffarekisteri line: 153", false, testi.onkoMuokattu()); 
    Leffa testi1 = new Leffa(); 
    testi.tallenna(testi1); 
    assertEquals("From: Leffarekisteri line: 156", true, testi.onkoMuokattu()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaLeffa176 
   * @throws IndexOutOfBoundsException when error
   * @throws SailoException when error
   */
  @Test
  public void testAnnaLeffa176() throws IndexOutOfBoundsException, SailoException {    // Leffarekisteri: 176
    Leffarekisteri leffarekisteri = new Leffarekisteri(); 
    Leffa l1 = new Leffa(); 
    Leffa l2 = new Leffa(); 
    assertEquals("From: Leffarekisteri line: 181", 0, leffarekisteri.getLeffoja()); 
    leffarekisteri.tallenna(l1); 
    assertEquals("From: Leffarekisteri line: 183", 1, leffarekisteri.getLeffoja()); 
    leffarekisteri.tallenna(l2); 
    assertEquals("From: Leffarekisteri line: 185", 2, leffarekisteri.getLeffoja()); 
    Leffa l3 = new Leffa(); 
    leffarekisteri.tallenna(l3); 
    assertEquals("From: Leffarekisteri line: 188", 3, leffarekisteri.getLeffoja()); 
    assertEquals("From: Leffarekisteri line: 189", l1, leffarekisteri.annaLeffa(0)); 
    assertEquals("From: Leffarekisteri line: 190", l2, leffarekisteri.annaLeffa(1)); 
    assertEquals("From: Leffarekisteri line: 191", l3, leffarekisteri.annaLeffa(2)); 
    try {
    leffarekisteri.annaLeffa(9); 
    fail("Leffarekisteri: 192 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    Leffa l4 = new Leffa(); 
    leffarekisteri.tallenna(l4); 
    assertEquals("From: Leffarekisteri line: 195", 4, leffarekisteri.getLeffoja()); 
    Leffa l5 = new Leffa(); 
    leffarekisteri.tallenna(l5); 
    assertEquals("From: Leffarekisteri line: 198", 5, leffarekisteri.getLeffoja()); 
    leffarekisteri.tallenna(l1); 
    assertEquals("From: Leffarekisteri line: 201", 5, leffarekisteri.getLeffoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLeffalleKuuluvatGenret332 
   * @throws SailoException when error
   */
  @Test
  public void testLeffalleKuuluvatGenret332() throws SailoException {    // Leffarekisteri: 332
    Leffarekisteri testi = new Leffarekisteri(); 
    Leffa testi1 = new Leffa(); 
    Genre komedia = new Genre(-1, "komedia"); 
    Genre satiiri = new Genre(-1, "satiiri"); 
    Genre kauhu = new Genre(-1, "kauhu"); 
    testi.tallenna(komedia); 
    testi.tallenna(satiiri); 
    testi.tallenna(kauhu); 
    testi.tallenna(testi1, new Genre[]{komedia, satiiri}); 
    ArrayList<Genre> genret = testi.leffalleKuuluvatGenret(testi1.getId()); 
    assertEquals("From: Leffarekisteri line: 345", 2, genret.size()); 
    testi.leffalleKuuluvatGenretPilkunKera(testi1.getId()).equals("komedia, satiiri"); 
  } // Generated by ComTest END
}