package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import movies.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:23:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LeffanGenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi42 */
  @Test
  public void testRekisteroi42() {    // LeffanGenre: 42
    LeffanGenre testi1 = new LeffanGenre(); 
    LeffanGenre testi2 = new LeffanGenre(); 
    testi1.setId(5); 
    testi2.rekisteroi(); 
    assertEquals("From: LeffanGenre line: 47", 5, testi1.getId()); 
    assertEquals("From: LeffanGenre line: 48", 6, testi2.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString97 */
  @Test
  public void testToString97() {    // LeffanGenre: 97
    LeffanGenre testi= new LeffanGenre(); 
    testi.parse("1|1|7"); 
    assertEquals("From: LeffanGenre line: 100", true, testi.toString().equals("1|1|7")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse112 */
  @Test
  public void testParse112() {    // LeffanGenre: 112
    LeffanGenre testi= new LeffanGenre(); 
    testi.parse("1|1|7"); 
    assertEquals("From: LeffanGenre line: 115", true, testi.toString().equals("1|1|7")); 
  } // Generated by ComTest END
}