package movies.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import movies.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.07.23 13:23:22 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LeffanGenretTest {



  // Generated by ComTest BEGIN
  /** testLeffanGenret16 */
  @Test
  public void testLeffanGenret16() {    // LeffanGenret: 16
    LeffanGenret testit = new LeffanGenret(); 
    LeffanGenre testi1 = new LeffanGenre(); 
    LeffanGenre testi2 = new LeffanGenre(); 
    int pohjaid = testi1.rekisteroi(); 
    testi2.rekisteroi(); 
    assertEquals("From: LeffanGenret line: 22", 0, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 24", 1, testit.getLkm()); 
    testit.lisaa(testi2); 
    assertEquals("From: LeffanGenret line: 26", 2, testit.getLkm()); 
    assertEquals("From: LeffanGenret line: 27", testi1, testit.getById(pohjaid++)); 
    assertEquals("From: LeffanGenret line: 28", testi2, testit.getById(pohjaid)); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 30", 3, testit.getLkm()); 
    assertEquals("From: LeffanGenret line: 31", testi1, testit.get(0)); 
    assertEquals("From: LeffanGenret line: 32", testi2, testit.get(1)); 
    assertEquals("From: LeffanGenret line: 33", testi1, testit.get(2)); 
    testit.lisaa(testi2); 
    assertEquals("From: LeffanGenret line: 35", 4, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 37", 5, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 39", 6, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 41", 7, testit.getLkm()); 
    testit.lisaa(testi1); 
    assertEquals("From: LeffanGenret line: 43", 8, testit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista74 */
  @Test
  public void testPoista74() {    // LeffanGenret: 74
    LeffanGenret testit = new LeffanGenret(); 
    LeffanGenre testi1 = new LeffanGenre(); 
    LeffanGenre testi2 = new LeffanGenre(); 
    LeffanGenre testi3 = new LeffanGenre(); 
    testi1.parse("1|1|1"); 
    testi2.parse("8|7|1"); 
    testi3.parse("10|8|1"); 
    testit.lisaa(testi1); 
    testit.lisaa(testi2); 
    testit.lisaa(testi3); 
    assertEquals("From: LeffanGenret line: 85", 3, testit.getLkm()); 
    testit.poista(1, 1); 
    assertEquals("From: LeffanGenret line: 87", 2, testit.getLkm()); 
    testit.poista(8, 1); 
    testit.poista(7, 2); 
    assertEquals("From: LeffanGenret line: 90", 1, testit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista102 */
  @Test
  public void testPoista102() {    // LeffanGenret: 102
    LeffanGenret testit = new LeffanGenret(); 
    LeffanGenre testi1 = new LeffanGenre(); 
    LeffanGenre testi2 = new LeffanGenre(); 
    LeffanGenre testi3 = new LeffanGenre(); 
    testi1.parse("1|1|1"); 
    testi2.parse("8|7|1"); 
    testi3.parse("10|8|1"); 
    testit.lisaa(testi1); 
    testit.lisaa(testi2); 
    testit.lisaa(testi3); 
    assertEquals("From: LeffanGenret line: 113", 3, testit.getLkm()); 
    testit.poista(1); 
    assertEquals("From: LeffanGenret line: 115", 2, testit.getLkm()); 
    testit.poista(8); 
    testit.poista(7); 
    assertEquals("From: LeffanGenret line: 118", 1, testit.getLkm()); 
  } // Generated by ComTest END
}